dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: mqube-apigw
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: quickstarttest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
